defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: rordev
  password: roruser

development:
  <<: *defaults
  database: simple_payroll_demo_dev

test:
  <<: *defaults
  database: simple_payroll_demo_test

production:
  <<: *defaults
  database: simple_payroll_demo_prod